### ISSUE TITLE
[Question] X11 on iOS - Which repo is the "Mine" repo? 

### ISSUE THREAD

**Issue by N-Olbert** [MaxLeiter/maxleiter.com#2]
Hi,

at the build instruction page of [X11 on iOS](https://maxleiter.com/X11/instructions) you mention a "mine" repository, which I am unable to find.

> From mine:
> automake
> autoconf
> ninja
> libpng
> gperf

May I ask where to find this files/libs and/or which source code base you used to build them (f. e. did you make any changes to these libs)?

Thanks :)

**Comment by TheAwesome98-Real** [comment]
http://maxleiter.github.io/cydia/
