### ISSUE TITLE
add RSS link somewhere on the page

### ISSUE THREAD

**Issue by reeseovine** [MaxLeiter/maxleiter.com#24]
i want to add your blog to my feed reader but i don't see an RSS link ~~(and didn't immediately find it in the source)~~ found it: https://maxleiter.com/feed.xml

maybe you should add it to the page so people can find it?

**Comment by MaxLeiter** [comment]
<img width="554" alt="image" src="https://user-images.githubusercontent.com/8675906/168665232-9a1f46fb-0b77-4d9e-b41f-10664ecc9ec7.png">

Thanks, added it to the homepage. It's also linked in the bottom of every post.

**Comment by reeseovine** [comment]
sweet, thanks!
