### ISSUE TITLE
Vercel deployment results in 500 error

### ISSUE THREAD

**Issue by nareshbhatia** [MaxLeiter/maxleiter.com#75]
Hi @MaxLeiter, thank you for making your site source available.

I am trying to make it work for me, but running into an issue. I am able to make both dev & prod builds run on my local machine without any issues. However, when I deploy on Vercel, I get a 500 error when I try to navigate to any blog post. See live app [here](https://blog-template-zeta.vercel.app/).

```
[Error: ENOENT: no such file or directory, scandir './posts/'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: './posts/'
}
```

Any idea why this is happening? My repo is here: https://github.com/nareshbhatia/blog-template

**Comment by nareshbhatia** [comment]
Found it. The issue was with `generateStaticParams()` to pre-render pages. I had started with the code in your blog which was as follows:

```ts
export async function generateStaticParams() {
  const posts = await getPosts()
  // The params to pre-render the page with.
  // Without this, the page will be rendered at runtime
  return posts.map((post) => ({ params: { slug: post.slug } }))
}
```

Looking at the actual code in your repo, the last line should be:

```ts
  return posts.map((post) => ({ slug: post.slug }));
```

This was causing pages not being pre-rendered and failing during runtime – the posts did not exist at `process.cwd()`.

You many want to fix your blog.

**Comment by MaxLeiter** [comment]
Interesting, great catch! I wonder why my blog works but yours doesn't

**Comment by nareshbhatia** [comment]
Mine is working now: https://blog-template-zeta.vercel.app/
